image: node:10

variables:
  NODE_ENV: ci
  NEAR_PROTOS_DIR: nearcore/runtime/protos/protos
  SKIP_DEV_CONNECT_TESTS: "true"
  SKIP_FAILED_ASSERT_TEST: "true"
  HELLO_WASM_PATH: nearcore/tests/hello.wasm

stages:
  - build
  - test

cache:
  paths:
    - nearcore/
    - node_modules/

install_dependencies:
  stage: build
  script:
    - rm -rf nearcore/ # nearcore/ gets cached
    - git clone --depth 1 --branch master https://github.com/nearprotocol/nearcore.git nearcore
    - rm -rf nearcore/nearlib
    - npm install
    - cd nearcore/tests/hello && npm install && npm run build
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script: NODE_ENV=development npm test

lint:
  stage: test
  script: npm run lint
