blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature request
    url: https://github.com/near/near-api-js/discussions
    about: Use GitHub discussions for feature requests.
  - name: â“ Simple question - Discord chat
    url: https://near.chat
    about: This issue tracker is not for technical support. Please use our Discord chat, and ask the community for help.
  - name: â“ Simple question - Stack Overflow
    url: https://stackoverflow.com/questions/tagged/nearprotocol
    about: This issue tracker is not for technical support. Please use Stack Overflow, and ask the community for help.
  - name: â“ Advanced question - GitHub Discussions
    url: https://github.com/near/near-api-js/discussions
    about: Use GitHub Discussions for advanced and unanswered questions only, requiring a maintainer's answer. Make sure the question wasn't already asked.
